# This workflow builds the JAR and uploads it as an asset to a new GitHub Release
# when you push a new version tag (e.g., v1.0.1).

name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow when you push a tag like v1.0.1

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to create a release.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        # This builds the project and creates tunnel.jar in the target/ directory
        run: mvn -B package --file pom.xml

      - name: Create GitHub Release and Upload JAR
        # This action creates a new release and attaches the JAR file to it.
        uses: softprops/action-gh-release@v1
        with:
          # The file to upload from the build directory.
          # Make sure this matches your pom.xml's <finalName>.
          files: target/tunnel.jar